spring:
  profiles:
    active: dev
  application:
    name: comment-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
    # Feign 熔断降级
    openfeign:
      circuitbreaker:
        enabled: true
  # MongoDB 配置
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true

server:
  port: 4400

# 日志配置
logging:
  level:
    root: info
    org.example: debug
