spring:
  profiles:
    active: dev
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  # Elasticsearch 配置
  elasticsearch:
    uris: ${ES_URIS}
    connection-timeout: 10s
    socket-timeout: 30s
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    # 消息确认机制
    publisher-confirm-type: correlated # 发送确认
    publisher-returns: true # 发送返回
    template:
      mandatory: true # 消息路由失败时返回给生产者
    listener:
      simple:
        acknowledge-mode: manual # 手动确认
        retry:
          enabled: true # 开启重试
          max-attempts: 3 # 最大重试次数

server:
  port: 4600

# 日志配置
logging:
  level:
    root: info
    org.example: debug
    org.elasticsearch: warn
