spring:
  cloud:
    gateway:
      routes: # 路由配置
        - id: auth-service
          uri: lb://auth-service # 路由的目标地址
          predicates: # 断言，判断请求是否符合要求
            - Path=/api/auth/** # 请求路径匹配

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/post/**,/api/posts/**

        - id: draft-service
          uri: lb://draft-service
          predicates:
            - Path=/api/draft/**

        - id: club-service
          uri: lb://club-service
          predicates:
            - Path=/api/club/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**,/api/users/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comment/**

        - id: rag-service
          uri: lb://rag-service
          predicates:
            - Path=/api/rag/**

        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/api/recommend/**

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**

        - id: chat-websocket
          uri: http://localhost:4302
          predicates:
            - Path=/socket.io/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
