spring:
  web:
    resources:
      static-locations: ${STATIC_LOCATIONS}
  profiles:
    active: dev
    include:
    - route
    - whitelist
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}

    sentinel:
      transport:
        port: 8719
        dashboard: ${SENTINEL_DASHBOARD}
  data:
    redis:
      timeout: 2000ms
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - X-User-Id
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
server:
  port: 80

logging:
  level:
    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG
    brave: DEBUG
    zipkin2: DEBUG