server:
  port: 4900

spring:
  application:
    name: rag-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# gRPC 客户端配置 — 通过 Nacos 发现 Python rag-py-service
grpc:
  client:
#    自定义的名字，和Client对应
    ragEngine:
      address: discovery:///rag-engine
      negotiation-type: PLAINTEXT
